### ISSUE TITLE
Setting up grafana on Kubernetes cluster

### ISSUE THREAD

**Issue by sauravraiguru** [bibinwilson/kubernetes-prometheus#12]
hey @bibinwilson @devopscube - have you documented any steps for setting up grafana on kubernetes cluster ?

**Comment by bibinwilson** [comment]
@sauravraiguru  not yet,..

**Comment by bibinwilson** [comment]
Closing this as the documentation is available now. https://devopscube.com/setup-grafana-kubernetes/
