### ISSUE TITLE
No graphs

### ISSUE THREAD

**Issue by vkuznet** [bibinwilson/kubernetes-prometheus#3]
Hi,
I read your blog post and followed all instructions. The prometheus service is up and running but I don't see any graphs. The only thing under Targets is a checkmark "Only unhealthy jobs". In a graph page I don't see any metrics either, e.g. if I enter kubernetes-nodes, I see "Load time" but nothing more.

My first question is:
- does it monitor apps/services in monitoring namespace or in all namespaces?
- I have few apps/pods/services running default namespace and I wonder may be I need to deploy prometheus in this specific namespace?
- the configuration file contains config for several endpoints and I wonder if something needs to be adjusted for specific cluster setup.

Thanks,
Valentin.

**Comment by vkuznet** [comment]
When I look at logs I found this:
```
level=error ts=2018-04-02T12:06:05.697527007Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:monitoring:default\" cannot list endpoints at the cluster scope"
level=error ts=2018-04-02T12:06:05.697874883Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:default\" cannot list pods at the cluster scope"
level=error ts=2018-04-02T12:06:05.698345346Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:354: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:monitoring:default\" cannot list nodes at the cluster scope"
```

**Comment by vkuznet** [comment]
Denis,
could you please elaborate more on this subject. My understanding that these are
the cluster rules which will allow prometheus to collect metrics from all
running services within k8s via /metrics end-point of the given service.
Am I right?
Thanks,
Valentin.

**Comment by bibinwilson** [comment]
@vkuznet Sorry for the confusion...I wrote the tutorial when kubernetes did not have a default RBAC enabled. Now kubernetes version comes with RBAC enabled. 
As @denisvmedia mentioned, you need to create a service account with cluster reader permissions. You can use the service account name during deployment.
I will update the article with service account creation.

Thanks @denisvmedia  for the update.

**Comment by vkuznet** [comment]
cool, I added aforementioned rules into kubernetes-prometheus/prometheus-service.yaml and I'm able to see now all the graphs. Thanks a lot.

**Comment by phong-ho** [comment]
> @vkuznet Sorry for the confusion...I wrote the tutorial when kubernetes did not have a default RBAC enabled. Now kubernetes version comes with RBAC enabled.
> As @denisvmedia mentioned, you need to create a service account with cluster reader permissions. You can use the service account name during deployment.
> I will update the article with service account creation.
> 
> Thanks @denisvmedia for the update.

@bibinwilson  have you updated the article with service account creation yet ?

**Comment by bibinwilson** [comment]
@phong-ho yes. there is a step to create the cluster role. And the cluster role manifest file is part of of this repo. https://github.com/bibinwilson/kubernetes-prometheus/blob/master/clusterRole.yaml

Are you facing any issue?

**Comment by phong-ho** [comment]
@bibinwilson  yes,  I have done all steps mentioned in this repo and https://devopscube.com/setup-prometheus-monitoring-on-kubernetes/ and https://devopscube.com/alert-manager-kubernetes-guide/. 
However, I got kubernetes-service-endpoints (2/4 up). in promethues --> Status -->Targets

![Capture](https://user-images.githubusercontent.com/50657881/62021519-d3ca5c80-b1f1-11e9-9208-0ebb6aa8cadf.JPG)

Labels : prometheus-service & alertmanager open the same port 8080. is it right ?

**Comment by bibinwilson** [comment]
@phong-ho I found the issue. You need to change the service endpoint discovery configurations in the config map.

here is the configuration which will discover all the service endpoints.

`      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name`

I have updated the configs in a branch for now as it requires few changes. Here is the full config map. https://github.com/bibinwilson/kubernetes-prometheus/blob/ISSUE-10/config-map.yaml
