### ISSUE TITLE
prometheus-service is down

### ISSUE THREAD

**Issue by rdrgporto** [bibinwilson/kubernetes-prometheus#6]
Hi,

First of all, thanks for this repository, it is very easy to understand and very practical. Secondly, when I deploy **Prometheus** in my **Kubernetes** environment (**kubeadm**), I have an error with **prometheus-service**. Here you are an screenshot:

![image](https://user-images.githubusercontent.com/6654666/44005286-4a449974-9e71-11e8-9569-18cb08839960.png)

Thanks in advance,

Regards

**Comment by bibinwilson** [comment]
@rdrgporto  please check if the cluster roles are created and applied to Prometheus deployment
